name: 'Download Godot'
description: 'Download Godot'
inputs:
  version:
    description: 'Version of godot to download'
    required: true
    default: '4.4'
runs:
  using: 'composite'
  steps:
    - name: Download Godot Templates
      uses: robinraju/release-downloader@v1
      with:
        repository: godotengine/godot
        tag: ${{ inputs.version }}-stable
        filename: Godot_v${{ inputs.version }}-stable_export_templates.tpz
    - name: Extract Godot Templates
      shell: bash
      env:
        BASE_PATH: ~/.local/share/godot/export_templates
        OUTPUT_PATH: ~/.local/share/godot/export_templates/${{ inputs.version }}.stable
      run: |
        mkdir -v -p $OUTPUT_PATH
        unzip Godot_v${{ inputs.version }}-stable_export_templates.tpz -d $BASE_PATH
        mv $BASE_PATH/templates/* $OUTPUT_PATH
        ls -l $OUTPUT_PATH
    
