# Variables:
#   ITCH_USER: The itch.io user to deploy to. (required)
#   ITCH_GAME: The itch.io game to deploy to. (required)
# Secrets:
#   BUTLER_API_KEY: The API key for butler. Required for deploying to itch.io. (required)
name: 'CI'
on:
  push:
    branches: [main]
jobs:
  build-game:
    uses: WesleyClements/godot-workflows/.github/workflows/build-game.yaml@main
    with:
      godot-version: '4.4'
      web-preset: 'Web'
      windows-preset: 'Windows Desktop'

  deploy-gh-pages:
    name: Deploy to GitHub Pages
    needs: [build-game]

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: ${{ needs.build-game.outputs.web-artifact-name }}


  deploy-itch:
    needs: [build-game]
    uses: WesleyClements/godot-workflows/.github/workflows/deploy-itch.yaml@main
    with:
      itch-user: ${{ vars.ITCH_USER }}
      itch-game: ${{ vars.ITCH_GAME }}
      game-version: 'version.txt'
      web-artifact-name: ${{ needs.build-game.outputs.web-artifact-name }}
      windows-artifact-name: ${{ needs.build-game.outputs.windows-artifact-name }}
    secrets:
      butler-api-key: ${{ secrets.BUTLER_API_KEY }}
